version: "3.9"

services:
  db:
    image: postgres:17
    container_name: webbshop_db
    environment:
      POSTGRES_DB: webbshop
      POSTGRES_USER: webbshop
      POSTGRES_PASSWORD: webbshop
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./WebbShopApi
      dockerfile: Dockerfile
    container_name: webbshop_api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: >
        Host=db;
        Port=5432;
        Database=webbshop;
        Username=webbshop;
        Password=webbshop
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webbshop_frontend
    ports:
      - "5173:8080"
    depends_on:
      - api

volumes:
  db_data: