version: "3.9"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webbshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webbshop_api:
    build:
      context: ./WebbShopApi
      dockerfile: Dockerfile
    container_name: webbshop_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=webbshop_db;Username=postgres;Password=postgres"
      Jwt__Key: "G9fQ2mX8P7sRkD4WZJcA1N5VYB6H0E3LhTUMaKpSnwqCxeoIOrF"
      Jwt__Issuer: "WebbShopApi"
      Jwt__Audience: "WebbShopUsers"
    depends_on:
      - postgres
    ports:
      - "5000:80"

volumes:
  postgres_data:
